export const scrollwiseSceneKeys = [
    "gateway", "discover", "design", "buildSecure", "oilGas", "petrochemical", "connectedOperations", "intelligence", "outcomes", "finale",
] as const;

export type ScrollwiseSceneKey = typeof scrollwiseSceneKeys[number];
export type ScrollwiseLanguage = "en" | "fa";
export type ScrollwiseCardCopy = {
    title: string;
    description: string;
    interludeTitle: string;
    interludeDescription: string;
    bridge: string;
    assistantPrompt: string;
};
export type ScrollwiseCopy = Record<ScrollwiseLanguage, Record<ScrollwiseSceneKey, ScrollwiseCardCopy>>;

export const defaultScrollwiseCopy: ScrollwiseCopy = {
    fa: {
        gateway: { title: "هر توقف بزرگ، از یک گسست کوچک آغاز می‌شود", description: "جایی میان میدان، کارخانه، مرکز داده و اتاق تصمیم، اطلاعات مسیر خود را گم می‌کند. آرندی دوباره میان فناوری، عملیات و انسان پیوند می‌سازد.", interludeTitle: "گسست‌های پنهان را پیدا کنیم", interludeDescription: "مسیر تحول با دیدن نقاطی آغاز می‌شود که داده، فرایند و تصمیم دیگر به هم نمی‌رسند.", bridge: "برای دیدن مسیر، ابتدا باید نشانه‌ها را بدون پیش‌داوری ببینیم.", assistantPrompt: "چگونه گلوگاه فناوری سازمانم را پیدا کنم؟" },
        discover: { title: "آنچه دیده نمی‌شود، قابل مدیریت نیست", description: "داده‌های پراکنده، فرایندهای ناپیوسته و تصمیم‌های دیرهنگام سه نشانه‌اند. گفت‌وگو، مشاهده میدانی و تحلیل وضع موجود از آن‌ها یک تصویر مشترک می‌سازد.", interludeTitle: "مسئله را پیش از انتخاب فناوری تعریف می‌کنیم", interludeDescription: "ارزیابی بلوغ، تحلیل فرایند و معماری وضع موجود، مبنای یک تصمیم اجرایی قابل دفاع می‌شود.", bridge: "وقتی مسئله برای همه یکسان دیده شود، می‌توان مسیر تغییر را طراحی کرد.", assistantPrompt: "برای ارزیابی بلوغ دیجیتال از کجا شروع کنم؟" },
        design: { title: "از تصویر مشترک، به یک نقشه مشترک", description: "وضع موجود، وضعیت مطلوب، اولویت‌ها، وابستگی‌ها و ریسک‌ها در یک نقشه‌راه مرحله‌بندی‌شده کنار هم قرار می‌گیرند.", interludeTitle: "راهی که پیش از اجرا قابل سنجش است", interludeDescription: "نقشه معماری، خروجی‌ها و ترتیب تحویل، گفت‌وگوی راهبردی را به برنامه‌ای قابل اجرا تبدیل می‌کند.", bridge: "نقشه زمانی ارزش دارد که عملیات روزمره بتواند با اطمینان بر آن بنا شود.", assistantPrompt: "یک نقشه‌راه تحول دیجیتال چه اجزایی دارد؟" },
        buildSecure: { title: "زیرساختی که عملیات بتواند به آن تکیه کند", description: "شبکه، مرکز داده، ابر، نرم‌افزار و امنیت مانند اجزای یک سیستم واحد، پایدار و قابل پایش ساخته می‌شوند.", interludeTitle: "یک بنیان امن برای مرحله بعد", interludeDescription: "دسترس‌پذیری، امنیت، مقیاس‌پذیری و بهره‌برداری روزمره باید هم‌زمان در معماری حضور داشته باشند.", bridge: "وقتی بنیان قابل اعتماد باشد، فناوری می‌تواند وارد قلب عملیات شود.", assistantPrompt: "برای طراحی زیرساخت چندسایتی از کجا شروع کنم؟" },
        oilGas: { title: "میدان و مرکز عملیات", description: "اطلاعات تجهیزات و ارتباطات صنعتی، ایمن و قابل اتکا به مرکز تصمیم می‌رسد تا فاصله میان رخداد و اقدام کوتاه شود.", interludeTitle: "فناوری در میدان", interludeDescription: "یک بنیان مشترک باید در سخت‌ترین فاصله‌های عملیاتی نیز قابل اتکا بماند.", bridge: "همان جریان قابل اعتماد، در کارخانه به کیفیت و نگهداری نزدیک می‌شود.", assistantPrompt: "آرندی در پروژه‌های نفت و گاز چه تجربه‌ای دارد؟" },
        petrochemical: { title: "کارخانه و آزمایشگاه", description: "داده آزمایشگاه، تجهیزات و برنامه‌ریزی تولید در یک نمای مشترک قرار می‌گیرد تا تصمیم‌ها دقیق‌تر و قابل پیگیری شوند.", interludeTitle: "از کیفیت تا برنامه‌ریزی", interludeDescription: "اطلاعات درست، میان کنترل کیفیت، نگهداری و تولید یک زبان مشترک ایجاد می‌کند.", bridge: "در مقیاس شبکه، همین زبان مشترک باید منابع متنوع را هماهنگ کند.", assistantPrompt: "یکپارچه‌سازی داده در کارخانه چه ارزشی ایجاد می‌کند؟" },
        connectedOperations: { title: "شبکه و منابع انرژی", description: "پایش شبکه، دارایی‌های تولید و منابع متنوع انرژی، یک تصویر عملیاتی مشترک برای هماهنگی روزمره می‌سازد.", interludeTitle: "یک بنیان؛ سه میدان عمل", interludeDescription: "در میدان، کارخانه و شبکه، اصل یکسان است: اطلاعات درست، در زمان درست، برای فرد درست.", bridge: "اکنون که داده قابل اعتماد و نزدیک به عملیات است، می‌توان آن را به تصمیم نزدیک‌تر کرد.", assistantPrompt: "آرندی برای عملیات انرژی چه راهکارهایی ارائه می‌کند؟" },
        intelligence: { title: "وقتی داده به تصمیم نزدیک می‌شود", description: "دستیار دانش سازمانی، نگهداری پیش‌بینانه، هوشمندسازی اسناد و تحلیل عملیات، توان کارشناسان را در یک چارچوب حاکمیت‌شده افزایش می‌دهند.", interludeTitle: "انسان در مرکز سازمان هوشمند باقی می‌ماند", interludeDescription: "هوش مصنوعی زمانی ارزش می‌سازد که داده قابل اعتماد، هدف روشن، نظارت انسانی و معیار قابل سنجش داشته باشد.", bridge: "هوشمندی زمانی پایدار است که هر روز بهره‌برداری، ارزیابی و بهتر شود.", assistantPrompt: "کدام کاربرد هوش مصنوعی برای سازمان من مناسب است؟" },
        outcomes: { title: "آنچه ساختیم، در عملیات ادامه پیدا می‌کند", description: "پروژه‌های واقعی پاسخ این روایت‌اند: بنیان یکپارچه، اتصال سایت و دفتر، محیط متصل و مدیریت پیشگیرانه عملیات چندسایتی.", interludeTitle: "اثبات، نه ادعا", interludeDescription: "نتیجه‌ها فقط از شواهد منتشرشده پروژه‌ها بیان می‌شوند؛ بدون عدد یا شاخصی که منبع قابل اتکا ندارد.", bridge: "هر تحویل، باید به قابلیتی تبدیل شود که مرحله بعدی رشد را ممکن کند.", assistantPrompt: "پروژه‌ای مشابه نیاز سازمانم را نشان بده." },
        finale: { title: "تحول یک پروژه نیست؛ قابلیتی است که باقی می‌ماند", description: "تصویر آغازین اکنون کامل است: جریان‌ها متصل‌اند، تصمیم به عملیات نزدیک است و سازمان می‌تواند مسیر بعدی را با اطمینان بسازد.", interludeTitle: "از یک گسست کوچک، تا یک تصویر کامل", interludeDescription: "پایان این روایت، نقطه آغاز گفت‌وگوی تحول سازمان شماست.", bridge: "مسیر بعدی را با یک گفت‌وگوی روشن آغاز کنیم.", assistantPrompt: "یک جلسه ارزیابی اولیه می‌خواهم." },
    },
    en: {
        gateway: { title: "Every major disruption begins with a small disconnect", description: "Somewhere between field, plant, data center and decision room, information loses its path. Arandi reconnects technology, operations and people.", interludeTitle: "Find the hidden disconnects", interludeDescription: "Transformation begins by seeing where data, process and decisions no longer meet.", bridge: "To see the path, we first observe the signals without preconceptions.", assistantPrompt: "How can I identify my organization's technology bottleneck?" },
        discover: { title: "What remains unseen cannot be managed", description: "Scattered data, broken workflows and delayed decisions are three signals. Dialogue, field observation and current-state analysis turn them into one shared picture.", interludeTitle: "Define the problem before choosing technology", interludeDescription: "Maturity assessment, process analysis and current-state architecture create a defensible basis for action.", bridge: "When everyone sees the same problem, the path of change can be designed.", assistantPrompt: "Where should a digital maturity assessment begin?" },
        design: { title: "From a shared picture to a shared blueprint", description: "Current state, target state, priorities, dependencies and risk become one phased transformation roadmap.", interludeTitle: "A path that can be tested before delivery", interludeDescription: "Architecture, outputs and delivery sequence turn strategy into an executable program.", bridge: "A blueprint matters when everyday operations can rely on what it builds.", assistantPrompt: "What belongs in a digital transformation roadmap?" },
        buildSecure: { title: "A foundation operations can rely on", description: "Network, data center, cloud, software and security are built as one resilient, observable system.", interludeTitle: "A secure foundation for what comes next", interludeDescription: "Availability, security, scale and everyday operation must coexist in the architecture.", bridge: "With a trusted foundation, technology can enter the heart of operations.", assistantPrompt: "Where should multi-site infrastructure design begin?" },
        oilGas: { title: "Field and operations center", description: "Industrial communications and equipment information reach the decision center securely and reliably, reducing the distance between event and action.", interludeTitle: "Technology in the field", interludeDescription: "A shared foundation must remain dependable across the hardest operational distances.", bridge: "The same trusted flow moves closer to quality and maintenance inside the plant.", assistantPrompt: "What experience does Arandi have in oil and gas projects?" },
        petrochemical: { title: "Plant and laboratory", description: "Laboratory, equipment and production-planning data form one shared view for decisions that are more precise and traceable.", interludeTitle: "From quality to planning", interludeDescription: "Trusted information creates a common language across quality, maintenance and production.", bridge: "At grid scale, the same common language must coordinate diverse resources.", assistantPrompt: "What value does plant data integration create?" },
        connectedOperations: { title: "Grid and energy resources", description: "Grid monitoring, generation assets and diverse resources form a shared operational picture for everyday coordination.", interludeTitle: "One foundation; three fields of action", interludeDescription: "Across field, plant and grid, the principle is the same: the right information, at the right time, for the right person.", bridge: "Now that data is trusted and close to operations, it can move closer to decisions.", assistantPrompt: "What solutions does Arandi provide for energy operations?" },
        intelligence: { title: "When data moves closer to decisions", description: "Enterprise knowledge assistants, predictive maintenance, document intelligence and operational analytics extend expert capability within a governed model.", interludeTitle: "People remain at the center of the intelligent enterprise", interludeDescription: "AI creates value with trusted data, a clear purpose, human oversight and measurable criteria.", bridge: "Intelligence becomes durable when it is operated, evaluated and improved every day.", assistantPrompt: "Which AI use case fits my organization?" },
        outcomes: { title: "What we build continues in operations", description: "Real projects answer the story: integrated foundations, connected project sites, reliable workplaces and proactive multi-site operations.", interludeTitle: "Evidence, not assertion", interludeDescription: "Outcomes are drawn only from published project evidence, never from unsupported numbers or claims.", bridge: "Every delivery should become a capability for the next stage of growth.", assistantPrompt: "Show me a project relevant to my organization." },
        finale: { title: "Transformation is not a project; it is a capability that remains", description: "The opening picture is now complete: flows connect, decisions move closer to operations and the organization can build its next stage with confidence.", interludeTitle: "From a small disconnect to the complete picture", interludeDescription: "The end of this story is the beginning of your transformation conversation.", bridge: "Begin the next path with a clear conversation.", assistantPrompt: "I would like an initial assessment session." },
    },
};
