ALTER TABLE "AnalyticsSession" ADD COLUMN IF NOT EXISTS "tokenHash" TEXT NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS "AnalyticsSession_tokenHash_key" ON "AnalyticsSession"("tokenHash");

UPDATE "SectionTranslation"
SET "description" = CASE "languageCode"
    WHEN 'fa' THEN E'ما فقط اطلاعات لازم برای پاسخ به درخواست‌ها، بهره‌برداری از وب‌سایت، حفاظت امنیتی و انجام الزامات قابل اجرا را جمع‌آوری می‌کنیم. اطلاعات شخصی فروخته نمی‌شود.\n\nدر صورت پذیرش آمار بازدید، مسیر صفحه، دامنهٔ ارجاع، زبان و دستهٔ تجمیعی دستگاه با شناسه‌های تصادفیِ شخص‌اول ثبت می‌شوند. برای تحلیل، IP یا User-Agent خام ذخیره نمی‌شود. شما می‌توانید آمار را رد کنید یا هر زمان تنظیمات حریم خصوصی را دوباره باز کنید.\n\nدسترسی به اطلاعات ارسالی به کارکنان و ارائه‌دهندگان مجازی محدود است که برای یک هدف تأییدشده به آن نیاز دارند. برای کاهش دسترسی غیرمجاز، از دست رفتن یا سوءاستفاده، تدابیر فنی و سازمانی متناسب اعمال می‌شود.\n\nبرای پرسش درباره اطلاعاتی که از طریق این وب‌سایت ارسال کرده‌اید می‌توانید با ما تماس بگیرید. این اطلاعیه ممکن است هم‌زمان با تغییر قابلیت‌های سایت یا الزامات مربوط به‌روزرسانی شود.'
    ELSE E'We collect only the information needed to respond to requests, operate the website, protect its security, and meet applicable obligations. We do not sell personal information.\n\nIf you accept website analytics, we record page paths, referral domain, language and aggregated device category using random first-party identifiers. We do not store IP addresses or raw browser user-agent values for analytics. You can decline analytics or reopen privacy preferences at any time.\n\nAccess to submitted information is limited to authorized personnel and service providers that need it for an approved purpose. Reasonable technical and organizational safeguards are used to reduce unauthorized access, loss, or misuse.\n\nYou may contact us to ask about information you submitted through this website. This notice may be updated when website capabilities or applicable requirements change.'
END
WHERE "sectionId" IN (SELECT "id" FROM "Section" WHERE "pageId" = (SELECT "id" FROM "Page" WHERE "slug" = 'privacy') AND "sectionType" = 'richText');
