"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";

import { cmsFetch } from "@/lib/admin/cms-fetch";
import { Button } from "@/components/ui/button";

type Reply = { id: string; createdAt: string; recipient: string; subject: string; body: string; deliveryState: string; deliveryAttempts: number };
type Submission = { id: string; reference: string; createdAt: string; fullName: string; email: string; organization: string | null; topic: string; message: string; languageCode: string; status: string; deliveryState: string; replies: Reply[] };
type Envelope<T> = { ok: boolean; data?: T; error?: { message?: string } };
async function envelope<T>(response: Response) { const body = await response.json() as Envelope<T>; if (!response.ok || !body.ok || body.data === undefined) throw new Error(body.error?.message ?? "Request failed."); return body.data; }
const statuses = ["received", "in_progress", "replied", "closed"];

export function AdminContactInbox() {
    const client = useQueryClient(); const [query, setQuery] = useState(""); const [selected, setSelected] = useState<string | null>(null); const [status, setStatus] = useState("");
    const inbox = useQuery({ queryKey: ["contact-inbox", query, status], queryFn: async () => envelope<Submission[]>(await fetch(`/api/cms/contact-submissions?days=90&query=${encodeURIComponent(query)}&status=${encodeURIComponent(status)}`, { cache: "no-store" })) });
    const refresh = () => client.invalidateQueries({ queryKey: ["contact-inbox"] });
    const update = useMutation({ mutationFn: async ({ id, next }: { id: string; next: string }) => envelope(await cmsFetch("/api/cms/contact-submissions", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id, status: next }) })), onSuccess: refresh });
    const current = inbox.data?.find((item) => item.id === selected) ?? inbox.data?.[0] ?? null;
    return <div className="grid gap-4 xl:grid-cols-[minmax(20rem,0.8fr)_minmax(28rem,1.2fr)]"><section className="rounded-2xl border border-border/70 bg-card p-4"><div className="flex flex-wrap gap-2"><label className="sr-only" htmlFor="contact-search">Search contact requests</label><input id="contact-search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search name, email, topic or reference" className="h-10 min-w-0 flex-1 rounded-xl border border-border/70 bg-background px-3 text-sm" /><label className="sr-only" htmlFor="contact-status">Filter status</label><select id="contact-status" value={status} onChange={(event) => setStatus(event.target.value)} className="h-10 rounded-xl border border-border/70 bg-background px-2 text-sm"><option value="">All statuses</option>{statuses.map((item) => <option key={item} value={item}>{item}</option>)}</select></div>{inbox.isLoading ? <p className="mt-5 text-sm text-muted-foreground">Loading requests…</p> : null}{inbox.isError ? <p role="alert" className="mt-5 text-sm text-destructive">{inbox.error.message}</p> : null}<ul className="mt-4 space-y-2">{inbox.data?.map((item) => <li key={item.id}><button type="button" onClick={() => setSelected(item.id)} className={`w-full rounded-xl border p-3 text-start transition-colors ${current?.id === item.id ? "border-primary bg-primary/5" : "border-border/70 hover:bg-muted/50"}`}><div className="flex items-center justify-between gap-3"><span className="font-semibold">{item.fullName}</span><span className="text-xs text-muted-foreground">{item.status}</span></div><p className="mt-1 truncate text-sm text-muted-foreground">{item.topic}</p><p className="mt-1 text-xs text-muted-foreground">{item.reference} · {new Date(item.createdAt).toLocaleDateString()}</p></button></li>)}</ul></section>{current ? <ContactDetails submission={current} onStatus={(next) => update.mutate({ id: current.id, next })} pending={update.isPending} onDone={refresh} /> : <section className="rounded-2xl border border-border/70 bg-card p-6 text-sm text-muted-foreground">No contact requests found.</section>}</div>;
}

function ContactDetails({ submission, onStatus, pending, onDone }: { submission: Submission; onStatus: (status: string) => void; pending: boolean; onDone: () => void }) {
    const [subject, setSubject] = useState(`Re: ${submission.topic}`); const [body, setBody] = useState(""); const [error, setError] = useState<string | null>(null); const [sent, setSent] = useState<string | null>(null);
    const reply = useMutation({ mutationFn: async () => envelope<Reply>(await cmsFetch(`/api/cms/contact-submissions/${submission.id}/replies`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ subject, body }) })), onSuccess: (value) => { setSent(value.deliveryState); setError(null); setBody(""); onDone(); }, onError: (value) => setError(value instanceof Error ? value.message : "Reply failed.") });
    const resend = useMutation({ mutationFn: async () => envelope(await cmsFetch(`/api/cms/contact-submissions/${submission.id}/notify`, { method: "POST" })), onSuccess: () => { setSent("notification resent"); setError(null); onDone(); }, onError: (value) => setError(value instanceof Error ? value.message : "Notification retry failed.") });
    return <section className="rounded-2xl border border-border/70 bg-card p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-semibold text-primary">{submission.reference}</p><h2 className="mt-1 text-lg font-semibold">{submission.topic}</h2><p className="mt-1 text-sm text-muted-foreground">{submission.fullName} · <a className="underline" href={`mailto:${submission.email}`}>{submission.email}</a></p></div><label className="grid gap-1 text-xs font-medium">Status<select value={submission.status} disabled={pending} onChange={(event) => onStatus(event.target.value)} className="h-9 rounded-lg border border-border bg-background px-2 text-sm">{statuses.map((item) => <option key={item} value={item}>{item}</option>)}</select></label></div><div className="mt-3 flex flex-wrap items-center gap-2 text-xs"><span className="rounded-full bg-muted px-3 py-1">Notification: {submission.deliveryState}</span>{submission.deliveryState !== "sent" ? <Button type="button" size="sm" variant="outline" disabled={resend.isPending} onClick={() => resend.mutate()}>{resend.isPending ? "Retrying…" : "Retry notification"}</Button> : null}</div><div className="mt-5 whitespace-pre-wrap rounded-xl bg-muted/50 p-4 text-sm leading-7">{submission.message}</div><div className="mt-5 space-y-3">{submission.replies.map((item) => <article key={item.id} className="rounded-xl border border-border/70 p-3 text-sm"><div className="flex flex-wrap justify-between gap-2"><p className="font-semibold">{item.subject}</p><span className="text-xs text-muted-foreground">{item.deliveryState}</span></div><p className="mt-2 whitespace-pre-wrap text-muted-foreground">{item.body}</p></article>)}</div><form className="mt-5 border-t border-border/70 pt-5" onSubmit={(event) => { event.preventDefault(); reply.mutate(); }}><h3 className="font-semibold">Reply by email</h3><label className="mt-3 grid gap-1.5 text-sm font-medium">Subject<input value={subject} onChange={(event) => setSubject(event.target.value)} required maxLength={200} className="h-10 rounded-xl border border-border/70 bg-background px-3" /></label><label className="mt-3 grid gap-1.5 text-sm font-medium">Message<textarea value={body} onChange={(event) => setBody(event.target.value)} required minLength={2} maxLength={8000} rows={7} className="rounded-xl border border-border/70 bg-background p-3" /></label>{error ? <p role="alert" className="mt-3 text-sm text-destructive">{error}</p> : null}{sent ? <p role="status" className="mt-3 text-sm text-primary">Reply recorded: {sent}.</p> : null}<div className="mt-4"><Button type="submit" disabled={reply.isPending}>{reply.isPending ? "Sending…" : "Send reply"}</Button></div></form></section>;
}
