import type { Language } from "../company";
import type {
    ArticleEntity,
    CareersEntity,
    CompanyEntity,
    ContactEntity,
    DomainContentModel,
    IndustryEntity,
    KnowledgeBaseEntity,
    PageEntity,
    ProjectEntity,
    ServiceEntity,
    SolutionEntity,
} from "./types";

function normalizeLanguage(lang?: string | null): Language {
    return lang === "fa" ? "fa" : "en";
}

function cms(id: string, locale: Language) {
    return {
        id,
        source: "local" as const,
        version: 1,
        locale,
        updatedAt: "2026-07-27",
    };
}

const domainContent: Record<Language, DomainContentModel> = {
    en: {
        language: "en",
        company: {
            id: "company-arandi-bonyan-en",
            slug: "arandi-bonyan",
            locale: "en",
            status: "published",
            cms: cms("company-arandi-bonyan-en", "en"),
            legalName: "Arandi Bonyan",
            shortName: "Arandi Bonyan",
            assistant: {
                name: "Jupiter",
                label: "Jupiter AI",
            },
        } satisfies CompanyEntity,
        services: [
            {
                id: "service-ai-en",
                slug: "artificial-intelligence",
                locale: "en",
                status: "published",
                cms: cms("service-ai-en", "en"),
                title: "Artificial Intelligence",
                summary: "Foundation for AI-enabled advisory, automation, and decision support journeys.",
                label: "1. Focus area",
            },
            {
                id: "service-infra-en",
                slug: "enterprise-it-infrastructure",
                locale: "en",
                status: "published",
                cms: cms("service-infra-en", "en"),
                title: "Enterprise IT Infrastructure",
                summary: "Foundation for modern infrastructure strategy, delivery, and operational resilience.",
                label: "2. Focus area",
            },
            {
                id: "service-transform-en",
                slug: "digital-transformation",
                locale: "en",
                status: "published",
                cms: cms("service-transform-en", "en"),
                title: "Digital Transformation",
                summary: "Foundation for transformation programs, technology adoption, and change enablement.",
                label: "3. Focus area",
            },
        ] satisfies ServiceEntity[],
        solutions: [
            {
                id: "solution-ai-roadmap-en",
                slug: "ai-roadmap",
                locale: "en",
                status: "published",
                cms: cms("solution-ai-roadmap-en", "en"),
                title: "Enterprise AI Readiness Roadmap",
                summary: "Assess capability maturity and define practical AI adoption milestones.",
                relatedServiceIds: ["service-ai-en", "service-transform-en"],
            },
            {
                id: "solution-platform-modernization-en",
                slug: "platform-modernization",
                locale: "en",
                status: "published",
                cms: cms("solution-platform-modernization-en", "en"),
                title: "Platform Modernization",
                summary: "Improve resilience and delivery speed across enterprise workloads.",
                relatedServiceIds: ["service-infra-en"],
            },
        ] satisfies SolutionEntity[],
        industries: [
            {
                id: "industry-finance-en",
                slug: "finance",
                locale: "en",
                status: "published",
                cms: cms("industry-finance-en", "en"),
                title: "Financial Services",
                summary: "Modernization and governance for regulated environments.",
            },
            {
                id: "industry-manufacturing-en",
                slug: "manufacturing",
                locale: "en",
                status: "published",
                cms: cms("industry-manufacturing-en", "en"),
                title: "Manufacturing",
                summary: "Operational visibility and automation across production systems.",
            },
        ] satisfies IndustryEntity[],
        projects: [
            {
                id: "project-digital-core-en",
                slug: "digital-core-refresh",
                locale: "en",
                status: "published",
                cms: cms("project-digital-core-en", "en"),
                title: "Digital Core Refresh",
                summary: "Enterprise platform refresh with AI-ready observability and governance.",
                industryIds: ["industry-finance-en"],
                solutionIds: ["solution-platform-modernization-en"],
                featured: true,
            },
        ] satisfies ProjectEntity[],
        articles: [
            {
                id: "article-ai-enterprise-en",
                slug: "ai-for-enterprise-operations",
                locale: "en",
                status: "published",
                cms: cms("article-ai-enterprise-en", "en"),
                title: "AI for Enterprise Operations",
                excerpt: "How to introduce AI into operations with measurable outcomes.",
                publishedAt: "2026-06-01",
                tags: ["ai", "operations", "enterprise"],
            },
        ] satisfies ArticleEntity[],
        knowledgeBase: [
            {
                id: "kb-architecture-priorities-en",
                slug: "architecture-priorities",
                locale: "en",
                status: "published",
                cms: cms("kb-architecture-priorities-en", "en"),
                question: "How should we prioritize AI and infrastructure initiatives?",
                answer: "Start with business-critical workflows, then scale through platform capabilities.",
                topics: ["strategy", "architecture"],
            },
        ] satisfies KnowledgeBaseEntity[],
        contact: {
            id: "contact-primary-en",
            slug: "contact",
            locale: "en",
            status: "published",
            cms: cms("contact-primary-en", "en"),
            primaryEmail: "hello@arandibonyan.com",
            primaryPhone: "+98 21 0000 0000",
            address: "Tehran, Iran",
        } satisfies ContactEntity,
        careers: {
            id: "careers-en",
            slug: "careers",
            locale: "en",
            status: "published",
            cms: cms("careers-en", "en"),
            title: "Build the future with us",
            summary: "Join teams shaping enterprise AI and digital transformation outcomes.",
            openings: [
                {
                    id: "opening-solution-architect-en",
                    title: "Solution Architect",
                    location: "Tehran",
                    type: "full-time",
                },
            ],
        } satisfies CareersEntity,
        pages: [
            {
                id: "page-home-en",
                slug: "home",
                locale: "en",
                status: "published",
                cms: cms("page-home-en", "en"),
                title: "Homepage",
                route: "/",
                seo: {
                    title: "Arandi Bonyan | Enterprise AI Assistant",
                    description: "Arandi Bonyan presents a bilingual enterprise experience centered on Jupiter AI and future-ready digital services.",
                    keywords: ["Arandi Bonyan", "enterprise AI", "Jupiter AI", "digital transformation"],
                },
                navigation: {
                    overviewLabel: "Overview",
                    capabilitiesLabel: "Capabilities",
                    contactLabel: "Contact",
                },
                footerTagline: "AI-ready enterprise foundation",
                sections: [
                    {
                        id: "hero",
                        type: "hero",
                        order: 1,
                        enabled: true,
                        badge: "Enterprise AI assistant",
                        title: "Jupiter; Your smart companion in the digital world",
                        description: "A modern perspective on organizational technology strategy; a clear path to digital transformation and infrastructure ready for the AI-powered future.",
                        primaryCta: "Explore Jupiter AI",
                        secondaryCta: "View capabilities",
                    },
                    {
                        id: "chat",
                        type: "chat",
                        order: 2,
                        enabled: true,
                        badge: "Jupiter AI",
                        heading: "Experience practical AI-based solutions on the path to your business’s digital transformation.",
                        description: "A polished interaction surface for future conversational workflows, designed for enterprise clarity.",
                        placeholder: "Start a conversation with Jupiter AI",
                        initialMessage: "I can help outline enterprise AI strategy, infrastructure planning, and transformation priorities.",
                        emptyStateTitle: "Start with a focused question.",
                        emptyStateDescription: "Ask about delivery priorities, enterprise architecture, or AI positioning.",
                        inputLabel: "Ask Jupiter AI",
                        inputPlaceholder: "Ask about infrastructure, AI, or transformation...",
                        inputAriaLabel: "Send message",
                        loadingText: "Preparing an enterprise response...",
                        assistantReply: "A focused response will be prepared here for future AI integration.",
                        assistantHint: "Ask about architecture, delivery, or AI readiness",
                    },
                    {
                        id: "features",
                        type: "features",
                        order: 3,
                        enabled: true,
                        eyebrow: "Capabilities",
                        title: "Structured foundation for future services and solutions.",
                        description: "This section provides an initial information architecture for upcoming offerings and partner engagement areas.",
                        serviceCardIds: ["service-ai-en", "service-infra-en", "service-transform-en"],
                    },
                ],
            },
        ] satisfies PageEntity[],
    },
    fa: {
        language: "fa",
        company: {
            id: "company-arandi-bonyan-fa",
            slug: "arandi-bonyan",
            locale: "fa",
            status: "published",
            cms: cms("company-arandi-bonyan-fa", "fa"),
            legalName: "آرن دی بنیان",
            shortName: "آرن دی بنیان",
            assistant: {
                name: "ژوپیتر",
                label: "ژوپیتر",
            },
        } satisfies CompanyEntity,
        services: [
            {
                id: "service-ai-fa",
                slug: "artificial-intelligence",
                locale: "fa",
                status: "published",
                cms: cms("service-ai-fa", "fa"),
                title: "هوش مصنوعی",
                summary: "بنیان برای مسیرهای مشاوره، خودکارسازی و پشتیبانی از تصمیمات با هوش مصنوعی.",
                label: "۱. حوزه تمرکز",
            },
            {
                id: "service-infra-fa",
                slug: "enterprise-it-infrastructure",
                locale: "fa",
                status: "published",
                cms: cms("service-infra-fa", "fa"),
                title: "زیرساخت فناوری سازمانی",
                summary: "بنیان برای استراتژی زیرساخت مدرن، اجرا و پایداری عملیاتی.",
                label: "۲. حوزه تمرکز",
            },
            {
                id: "service-transform-fa",
                slug: "digital-transformation",
                locale: "fa",
                status: "published",
                cms: cms("service-transform-fa", "fa"),
                title: "تحول دیجیتال",
                summary: "بنیان برای برنامه‌های تحول، پذیرش فناوری و توانمندسازی تغییر.",
                label: "۳. حوزه تمرکز",
            },
        ] satisfies ServiceEntity[],
        solutions: [
            {
                id: "solution-ai-roadmap-fa",
                slug: "ai-roadmap",
                locale: "fa",
                status: "published",
                cms: cms("solution-ai-roadmap-fa", "fa"),
                title: "نقشه راه آمادگی هوش مصنوعی سازمانی",
                summary: "ارزیابی بلوغ قابلیت‌ها و تعریف نقاط عطف عملی برای پذیرش هوش مصنوعی.",
                relatedServiceIds: ["service-ai-fa", "service-transform-fa"],
            },
            {
                id: "solution-platform-modernization-fa",
                slug: "platform-modernization",
                locale: "fa",
                status: "published",
                cms: cms("solution-platform-modernization-fa", "fa"),
                title: "نوسازی پلتفرم",
                summary: "بهبود تاب‌آوری و سرعت تحویل در بارهای کاری سازمانی.",
                relatedServiceIds: ["service-infra-fa"],
            },
        ] satisfies SolutionEntity[],
        industries: [
            {
                id: "industry-finance-fa",
                slug: "finance",
                locale: "fa",
                status: "published",
                cms: cms("industry-finance-fa", "fa"),
                title: "خدمات مالی",
                summary: "نوسازی و حاکمیت برای محیط‌های قانون‌مند.",
            },
            {
                id: "industry-manufacturing-fa",
                slug: "manufacturing",
                locale: "fa",
                status: "published",
                cms: cms("industry-manufacturing-fa", "fa"),
                title: "تولید",
                summary: "دیدپذیری عملیاتی و خودکارسازی در سامانه‌های تولید.",
            },
        ] satisfies IndustryEntity[],
        projects: [
            {
                id: "project-digital-core-fa",
                slug: "digital-core-refresh",
                locale: "fa",
                status: "published",
                cms: cms("project-digital-core-fa", "fa"),
                title: "بازآفرینی هسته دیجیتال",
                summary: "نوسازی پلتفرم سازمانی با رصدپذیری و حاکمیت آماده برای هوش مصنوعی.",
                industryIds: ["industry-finance-fa"],
                solutionIds: ["solution-platform-modernization-fa"],
                featured: true,
            },
        ] satisfies ProjectEntity[],
        articles: [
            {
                id: "article-ai-enterprise-fa",
                slug: "ai-for-enterprise-operations",
                locale: "fa",
                status: "published",
                cms: cms("article-ai-enterprise-fa", "fa"),
                title: "هوش مصنوعی برای عملیات سازمانی",
                excerpt: "چگونه هوش مصنوعی را با نتایج قابل اندازه‌گیری وارد عملیات کنیم.",
                publishedAt: "2026-06-01",
                tags: ["هوش مصنوعی", "عملیات", "سازمانی"],
            },
        ] satisfies ArticleEntity[],
        knowledgeBase: [
            {
                id: "kb-architecture-priorities-fa",
                slug: "architecture-priorities",
                locale: "fa",
                status: "published",
                cms: cms("kb-architecture-priorities-fa", "fa"),
                question: "چگونه باید ابتکارهای هوش مصنوعی و زیرساخت را اولویت‌بندی کنیم؟",
                answer: "از جریان‌های کاری حیاتی کسب‌وکار شروع کنید و سپس از طریق قابلیت‌های پلتفرمی مقیاس دهید.",
                topics: ["راهبرد", "معماری"],
            },
        ] satisfies KnowledgeBaseEntity[],
        contact: {
            id: "contact-primary-fa",
            slug: "contact",
            locale: "fa",
            status: "published",
            cms: cms("contact-primary-fa", "fa"),
            primaryEmail: "hello@arandibonyan.com",
            primaryPhone: "+98 21 0000 0000",
            address: "تهران، ایران",
        } satisfies ContactEntity,
        careers: {
            id: "careers-fa",
            slug: "careers",
            locale: "fa",
            status: "published",
            cms: cms("careers-fa", "fa"),
            title: "آینده را با ما بسازید",
            summary: "به تیم‌هایی بپیوندید که نتایج هوش مصنوعی و تحول دیجیتال سازمانی را شکل می‌دهند.",
            openings: [
                {
                    id: "opening-solution-architect-fa",
                    title: "معمار راهکار",
                    location: "تهران",
                    type: "full-time",
                },
            ],
        } satisfies CareersEntity,
        pages: [
            {
                id: "page-home-fa",
                slug: "home",
                locale: "fa",
                status: "published",
                cms: cms("page-home-fa", "fa"),
                title: "صفحه اصلی",
                route: "/",
                seo: {
                    title: "آرن دی بنیان | دستیار هوش مصنوعی سازمانی",
                    description: "آرن دی بنیان تجربه‌ای دوزبانه و سازمانی برای ژوپیتر و خدمات دیجیتال آماده‌ی آینده ارائه می‌دهد.",
                    keywords: ["آرن دی بنیان", "هوش مصنوعی سازمانی", "ژوپیتر", "تحول دیجیتال"],
                },
                navigation: {
                    overviewLabel: "معرفی",
                    capabilitiesLabel: "توانمندی‌ها",
                    contactLabel: "تماس",
                },
                footerTagline: "بنیاد سازمانی آماده برای هوش مصنوعی",
                sections: [
                    {
                        id: "hero",
                        type: "hero",
                        order: 1,
                        enabled: true,
                        badge: "دستیار هوش مصنوعی سازمانی",
                        title: "ژوپیتر؛ همراه هوشمند شما در دنیای دیجیتال",
                        description: "نگاهی نو به راهبرد فناوری سازمان‌ها؛ مسیری روشن برای تحول دیجیتال و زیرساختی آماده برای آینده‌ی هوش مصنوعی.",
                        primaryCta: "کاوش در Jupiter AI",
                        secondaryCta: "مشاهده توانمندی‌ها",
                    },
                    {
                        id: "chat",
                        type: "chat",
                        order: 2,
                        enabled: true,
                        badge: "ژوپیتر",
                        heading: "راهکارهای کاربردی مبتنی بر هوش مصنوعی را در مسیر تحول دیجیتال کسب‌وکارتان تجربه کنید.",
                        description: "یک تجربه تعاملی منظم برای جریان‌های آینده‌ی گفت‌وگوی هوش مصنوعی، طراحی‌شده برای شفافیت سازمانی.",
                        placeholder: "با Jupiter AI گفتگو را آغاز کنید",
                        initialMessage: "می‌توانم در زمینه استراتژی هوش مصنوعی سازمانی، برنامه‌ریزی زیرساخت و اولویت‌های تحول راهنمایی کنم.",
                        emptyStateTitle: "با یک پرسش متمرکز شروع کنید.",
                        emptyStateDescription: "در مورد اولویت‌های اجرایی، معماری سازمانی یا موقعیت هوش مصنوعی بپرسید.",
                        inputLabel: "از Jupiter AI بپرسید",
                        inputPlaceholder: "در مورد زیرساخت، هوش مصنوعی یا تحول بپرسید...",
                        inputAriaLabel: "ارسال پیام",
                        loadingText: "در حال آماده‌سازی پاسخ سازمانی...",
                        assistantReply: "پاسخی متمرکز برای ادغام آینده‌ای هوش مصنوعی آماده می‌شود.",
                        assistantHint: "در مورد معماری، اجرا یا آمادگی هوش مصنوعی بپرسید",
                    },
                    {
                        id: "features",
                        type: "features",
                        order: 3,
                        enabled: true,
                        eyebrow: "توانمندی‌ها",
                        title: "بنیان ساختاریافته برای خدمات و راه‌حل‌های آینده.",
                        description: "این بخش یک معماری اولیه‌ی اطلاعات برای ارائه‌های آینده و حوزه‌های همکاری با شرکای تجاری فراهم می‌کند.",
                        serviceCardIds: ["service-ai-fa", "service-infra-fa", "service-transform-fa"],
                    },
                ],
            },
        ] satisfies PageEntity[],
    },
};

export function getDomainContentModel(lang?: string | null): DomainContentModel {
    return domainContent[normalizeLanguage(lang)];
}
