import { Prisma } from "@prisma/client";

import { prisma } from "@/lib/prisma";

type Language = "en" | "fa";
type Localized<T> = Record<Language, T>;
type CollectionKey = "services" | "solutions" | "industries" | "projects";

const json = (value: unknown): Prisma.InputJsonValue => value as Prisma.InputJsonValue;

const copy = {
    company: {
        en: {
            title: "Arandi | Digital Transformation Partner",
            description: "Arandi designs and delivers dependable IT infrastructure, cybersecurity, cloud, enterprise systems, managed services, and AI solutions.",
            payload: {
                breadcrumbLabel: "Company",
                hero: { badge: "Digital Transformation Partner", title: "From infrastructure to intelligence", description: "Arandi combines engineering expertise, practical delivery, and research to help organizations build secure, reliable, and future-ready digital capabilities.", primaryAction: "Start a conversation", secondaryAction: "Explore services" },
                overview: { eyebrow: "Company Profile", title: "Committed to Results", description: "Arandi is a digital transformation partner for forward-looking organizations. We bring together engineering, execution, and research to turn technology into measurable business value.", highlights: ["IT infrastructure and secure connectivity", "Cloud, modern computing, and managed services", "Enterprise systems and applied artificial intelligence"] },
                missionVision: { eyebrow: "Mission & Vision", title: "Technology that creates durable value", missionTitle: "Our mission", missionText: "To help organizations achieve digital transformation through engineered IT, infrastructure, and AI solutions with quality, security, reliability, and measurable results.", visionTitle: "Our vision", visionText: "To be a trusted digital transformation partner in the region for organizations building sustainable, intelligent, and resilient operations." },
                coreValues: { eyebrow: "Core Values", title: "Principles behind every engagement", values: [{ title: "Committed to Results", description: "We define success through outcomes that matter to the organization." }, { title: "Quality Without Compromise", description: "Engineering quality and reliable delivery guide every decision." }, { title: "Trust & Transparency", description: "We work with clear communication and accountable collaboration." }, { title: "Security by Design", description: "Security is built into architecture, not added at the end." }, { title: "Research & Innovation", description: "We apply current knowledge to practical organizational needs." }, { title: "Long-Term Partnership", description: "We support capabilities that remain useful beyond project delivery." }] },
                whyArandi: { eyebrow: "Why Arandi", title: "Built for complex organizational realities", points: ["Strategy, architecture, implementation, security, intelligence, and operations in one delivery path", "Solutions designed around real processes, constraints, and future growth", "A long-term partnership model focused on measurable outcomes"] },
                cta: { eyebrow: "Next step", title: "Start with your current priorities", description: "Tell us about your organization’s goals, constraints, and critical services so we can shape a practical path forward.", action: "Contact Arandi" },
            },
        },
        fa: {
            title: "آرندی | شریک تحول دیجیتال",
            description: "آرندی راهکارهای زیرساخت فناوری اطلاعات، امنیت سایبری، رایانش ابری، سامانه‌های سازمانی، خدمات مدیریت‌شده و هوش مصنوعی را طراحی و اجرا می‌کند.",
            payload: {
                breadcrumbLabel: "شرکت",
                hero: { badge: "شریک تحول دیجیتال", title: "از زیرساخت تا هوشمندی", description: "آرندی با تلفیق دانش مهندسی، توان اجرا و نگاه پژوهشی، به سازمان‌ها کمک می‌کند تا قابلیت‌های دیجیتال امن، پایدار و آمادهٔ آینده بسازند.", primaryAction: "شروع گفت‌وگو", secondaryAction: "مشاهده خدمات" },
                overview: { eyebrow: "معرفی شرکت", title: "متعهد به نتیجه", description: "آرندی شریک تحول دیجیتال سازمان‌های پیشرو است. ما مهندسی، اجرا و پژوهش را کنار هم قرار می‌دهیم تا فناوری به ارزشی قابل‌اندازه‌گیری برای کسب‌وکار تبدیل شود.", highlights: ["زیرساخت فناوری اطلاعات و ارتباطات امن", "رایانش ابری، زیرساخت مدرن و خدمات مدیریت‌شده", "سامانه‌های سازمانی و هوش مصنوعی کاربردی"] },
                missionVision: { eyebrow: "ماموریت و چشم‌انداز", title: "فناوری برای خلق ارزش پایدار", missionTitle: "ماموریت ما", missionText: "کمک به سازمان‌ها برای دستیابی به تحول دیجیتال از طریق راهکارهای مهندسی‌شدهٔ فناوری اطلاعات، زیرساخت و هوش مصنوعی با کیفیت، امنیت، پایداری و نتایج قابل‌اندازه‌گیری.", visionTitle: "چشم‌انداز ما", visionText: "تبدیل‌شدن به شریکی قابل‌اعتماد در تحول دیجیتال منطقه برای سازمان‌هایی که عملیات پایدار، هوشمند و آینده‌نگر می‌سازند." },
                coreValues: { eyebrow: "ارزش‌های بنیادین", title: "اصول راهنمای هر همکاری", values: [{ title: "تعهد به نتیجه", description: "موفقیت را با دستاوردهای مهم برای سازمان تعریف می‌کنیم." }, { title: "کیفیت بدون مصالحه", description: "کیفیت مهندسی و تحویل قابل‌اعتماد، مبنای تصمیم‌های ماست." }, { title: "اعتماد و شفافیت", description: "با ارتباط روشن و همکاری مسئولانه پیش می‌رویم." }, { title: "امنیت در طراحی", description: "امنیت از ابتدا در معماری است، نه افزوده‌ای در پایان." }, { title: "پژوهش و نوآوری", description: "دانش روز را برای نیازهای واقعی سازمان به‌کار می‌گیریم." }, { title: "مشارکت بلندمدت", description: "قابلیت‌هایی می‌سازیم که پس از تحویل پروژه نیز ارزشمند بمانند." }] },
                whyArandi: { eyebrow: "چرا آرندی", title: "ساخته‌شده برای واقعیت‌های پیچیدهٔ سازمانی", points: ["راهبرد، معماری، اجرا، امنیت، هوشمندی و بهره‌برداری در یک مسیر تحویل", "راهکارهایی متناسب با فرآیندها، محدودیت‌ها و رشد آیندهٔ هر سازمان", "مدل مشارکت بلندمدت با تمرکز بر نتایج قابل‌اندازه‌گیری"] },
                cta: { eyebrow: "گام بعد", title: "از اولویت‌های امروزتان شروع کنیم", description: "اهداف، محدودیت‌ها و سرویس‌های حیاتی سازمانتان را با ما در میان بگذارید تا مسیری عملی برای پیش‌روی طراحی کنیم.", action: "تماس با آرندی" },
            },
        },
    },
    contact: {
        en: { title: "Contact Arandi", description: "Talk with Arandi about digital transformation, IT infrastructure, cybersecurity, cloud, enterprise systems, managed services, or AI.", payload: { breadcrumbLabel: "Contact", hero: { badge: "Contact Arandi", title: "Let’s discuss your next priority", description: "Reach our team to begin a conversation about your organization’s technology, infrastructure, and intelligent transformation needs." }, methods: { eyebrow: "Contact channels", title: "Reach our team", description: "Use the channel that works best for an initial coordination.", items: [{ key: "email", label: "Email", note: "info@arandi.io" }, { key: "phone", label: "Phone", note: "+98 21 8609 5567" }, { key: "location", label: "Head office", note: "Tehran, Jahanara Street, 23rd Street, No. 31, Unit 4" }] }, office: { eyebrow: "Office information", title: "Tehran office", businessHoursTitle: "Business hours", businessHoursValue: "Sunday to Thursday, 9:00 AM to 5:00 PM", responseTimeTitle: "Initial response", responseTimeValue: "Within one business day for new inquiries" }, form: { eyebrow: "Engagement request", title: "Tell us about your needs", description: "Share a short brief and our team will prepare for an informed first discussion.", labels: { fullName: "Full name", workEmail: "Work email", organization: "Organization", topic: "Request topic", message: "Project brief" }, placeholders: { fullName: "Your full name", workEmail: "name@company.com", organization: "Organization name", topic: "Example: infrastructure modernization", message: "Share your goals, constraints, and expected timeline" }, note: "Your information is used only to respond to your inquiry." }, cta: { eyebrow: "Get started", title: "Begin with one critical challenge", description: "We will align the first conversation with your strategic and operational priorities.", action: "Send inquiry" } } },
        fa: { title: "تماس با آرندی", description: "برای گفت‌وگو دربارهٔ تحول دیجیتال، زیرساخت فناوری اطلاعات، امنیت سایبری، رایانش ابری، سامانه‌های سازمانی، خدمات مدیریت‌شده یا هوش مصنوعی با آرندی در تماس باشید.", payload: { breadcrumbLabel: "تماس", hero: { badge: "تماس با آرندی", title: "دربارهٔ اولویت بعدی‌تان گفت‌وگو کنیم", description: "برای آغاز گفت‌وگو دربارهٔ نیازهای فناوری، زیرساخت و تحول هوشمند سازمان خود با تیم آرندی ارتباط بگیرید." }, methods: { eyebrow: "راه‌های ارتباط", title: "با تیم ما در تماس باشید", description: "برای هماهنگی اولیه از هرکدام از راه‌های زیر استفاده کنید.", items: [{ key: "email", label: "ایمیل", note: "info@arandi.io" }, { key: "phone", label: "تلفن", note: "۰۲۱-۸۶۰۹۵۵۶۷" }, { key: "location", label: "دفتر مرکزی", note: "تهران، خیابان جهان‌آرا، خیابان بیست‌وسوم، پلاک ۳۱، واحد ۴" }] }, office: { eyebrow: "اطلاعات دفتر", title: "دفتر تهران", businessHoursTitle: "ساعات کاری", businessHoursValue: "شنبه تا پنج‌شنبه، ۹ تا ۱۷", responseTimeTitle: "پاسخ اولیه", responseTimeValue: "حداکثر یک روز کاری برای درخواست‌های جدید" }, form: { eyebrow: "درخواست همکاری", title: "نیاز خود را با ما در میان بگذارید", description: "شرح کوتاهی از نیازتان بنویسید تا تیم ما برای یک گفت‌وگوی اولیهٔ آگاهانه آماده شود.", labels: { fullName: "نام و نام خانوادگی", workEmail: "ایمیل کاری", organization: "سازمان", topic: "موضوع درخواست", message: "شرح پروژه" }, placeholders: { fullName: "نام و نام خانوادگی", workEmail: "name@company.com", organization: "نام سازمان", topic: "نمونه: نوسازی زیرساخت", message: "اهداف، محدودیت‌ها و زمان‌بندی مورد انتظار را بنویسید" }, note: "اطلاعات شما فقط برای پاسخ‌گویی به درخواستتان استفاده می‌شود." }, cta: { eyebrow: "شروع همکاری", title: "از یک چالش مهم آغاز کنیم", description: "نخستین گفت‌وگو را با توجه به اولویت‌های راهبردی و عملیاتی شما تنظیم می‌کنیم.", action: "ارسال درخواست" } } },
    },
} as const;

const collections: Record<CollectionKey, Localized<{ title: string; description: string; payload: Record<string, unknown>; cards: Array<{ id: string; title: string; description: string; secondary?: string; badge?: string }> }>> = {
    services: {
        en: { title: "Services", description: "Engineering-led technology services spanning transformation, infrastructure, cloud, cybersecurity, enterprise systems, AI, and managed operations.", payload: { breadcrumbLabel: "Services", hero: { badge: "Arandi capabilities", title: "Technology services from infrastructure to intelligence", description: "Seven connected capabilities help organizations plan, build, secure, transform, and operate their digital environment.", primaryAction: "Explore solutions", secondaryAction: "Contact us" }, section: { eyebrow: "Service portfolio", title: "Capabilities for durable digital transformation", description: "Each capability can stand alone or form part of an integrated transformation path." }, cta: { eyebrow: "Start with context", title: "Select the right capability mix", description: "We assess your current environment and identify the most practical next steps.", action: "Request a consultation" } }, cards: [
            { id: "digital-transformation-consulting", badge: "Strategy & consulting", title: "Digital Transformation & IT Consulting", description: "IT strategy, maturity assessment, digital roadmaps, enterprise architecture, technology selection, risk analysis, and AI consultation." },
            { id: "infrastructure-network-data-center", badge: "Infrastructure", title: "Infrastructure, Network & Data Center", description: "Data centers, server rooms, structured cabling, LAN/WAN, wireless and radio networks, and secure connections between sites." },
            { id: "cloud-modern-infrastructure", badge: "Cloud & computing", title: "Cloud, Servers & Modern Infrastructure", description: "Enterprise servers, storage, virtualization, private and hybrid cloud, high availability, load balancing, and growth-ready capacity." },
            { id: "cybersecurity-business-continuity", badge: "Security", title: "Cybersecurity & Business Continuity", description: "Security architecture, identity and access management, network segmentation, backup, disaster recovery, and service continuity planning." },
            { id: "enterprise-solutions", badge: "Enterprise systems", title: "Enterprise Solutions", description: "VoIP, contact centers, unified communications, organizational websites and portals, email, CCTV, and access-control integration." },
            { id: "ai-solutions", badge: "Artificial intelligence", title: "Artificial Intelligence Solutions", description: "AI strategy, intelligent agents, enterprise assistants, knowledge management, smart search, process automation, document intelligence, and analytics." },
            { id: "managed-it-services", badge: "Managed operations", title: "Managed IT Services", description: "Technical support, help desk, monitoring, preventive maintenance, documentation, reporting, and service-level management." },
        ] },
        fa: { title: "خدمات", description: "خدمات مهندسی‌شدهٔ آرندی در تحول دیجیتال، زیرساخت، رایانش ابری، امنیت سایبری، سامانه‌های سازمانی، هوش مصنوعی و بهره‌برداری مدیریت‌شده.", payload: { breadcrumbLabel: "خدمات", hero: { badge: "توانمندی‌های آرندی", title: "خدمات فناوری از زیرساخت تا هوشمندی", description: "هفت توانمندیِ پیوسته به سازمان‌ها کمک می‌کنند تا محیط دیجیتال خود را طراحی، اجرا، ایمن، متحول و بهره‌برداری کنند.", primaryAction: "مشاهده راهکارها", secondaryAction: "تماس با ما" }, section: { eyebrow: "سبد خدمات", title: "توانمندی‌هایی برای تحول دیجیتال پایدار", description: "هر توانمندی می‌تواند مستقل یا به‌عنوان بخشی از یک مسیر یکپارچهٔ تحول ارائه شود." }, cta: { eyebrow: "شروع از واقعیت", title: "ترکیب مناسب توانمندی‌ها را انتخاب کنید", description: "محیط فعلی شما را ارزیابی می‌کنیم و عملی‌ترین گام‌های بعدی را پیشنهاد می‌دهیم.", action: "درخواست مشاوره" } }, cards: [
            { id: "digital-transformation-consulting", badge: "راهبرد و مشاوره", title: "مشاوره تحول دیجیتال و فناوری اطلاعات", description: "راهبرد IT، ارزیابی بلوغ، نقشه‌راه دیجیتال، معماری سازمانی، انتخاب فناوری، تحلیل ریسک و مشاوره هوش مصنوعی." },
            { id: "infrastructure-network-data-center", badge: "زیرساخت", title: "زیرساخت، شبکه و مرکز داده", description: "مرکز داده و اتاق سرور، کابل‌کشی ساخت‌یافته، LAN/WAN، شبکه بی‌سیم و رادیویی و اتصال امن میان سایت‌ها." },
            { id: "cloud-modern-infrastructure", badge: "ابر و پردازش", title: "رایانش ابری، سرورها و زیرساخت مدرن", description: "سرور و ذخیره‌سازی سازمانی، مجازی‌سازی، ابر خصوصی و هیبریدی، دسترس‌پذیری بالا، توازن بار و ظرفیت آمادهٔ رشد." },
            { id: "cybersecurity-business-continuity", badge: "امنیت", title: "امنیت سایبری و تداوم کسب‌وکار", description: "معماری امنیت، مدیریت هویت و دسترسی، تفکیک شبکه، پشتیبان‌گیری، بازیابی از بحران و برنامه‌ریزی تداوم خدمات." },
            { id: "enterprise-solutions", badge: "سامانه‌های سازمانی", title: "راهکارهای سازمانی", description: "VoIP، مرکز تماس، ارتباطات یکپارچه، وب‌سایت و پرتال سازمانی، ایمیل، نظارت تصویری و یکپارچه‌سازی کنترل تردد." },
            { id: "ai-solutions", badge: "هوش مصنوعی", title: "راهکارهای هوش مصنوعی", description: "راهبرد AI، عامل‌ها و دستیارهای هوشمند، مدیریت دانش، جست‌وجوی هوشمند، اتوماسیون فرایند، هوشمندسازی اسناد و تحلیل داده." },
            { id: "managed-it-services", badge: "بهره‌برداری مدیریت‌شده", title: "خدمات مدیریت‌شده فناوری اطلاعات", description: "پشتیبانی فنی، هلپ‌دسک، مانیتورینگ، نگهداری پیشگیرانه، مستندسازی، گزارش‌دهی و مدیریت سطح خدمات." },
        ] },
    },
    industries: {
        en: { title: "Industries", description: "Industry-specific technology foundations for energy, manufacturing, financial institutions, government, healthcare, and multi-site enterprises.", payload: { breadcrumbLabel: "Industries", hero: { badge: "Industries we serve", title: "Solutions shaped by industry reality", description: "We begin with the processes, constraints, and strategic goals of each sector—not a pre-packaged technology stack.", primaryAction: "Explore services", secondaryAction: "View projects" }, section: { eyebrow: "Target industries", title: "Technology aligned with operational context", description: "Architecture and delivery priorities are tailored to the conditions that matter in each industry." }, cta: { eyebrow: "Industry alignment", title: "Plan for your sector’s realities", description: "Start with a focused assessment of critical operations, risks, and growth opportunities.", action: "Request an assessment" } }, cards: [
            { id: "energy-petrochemicals", title: "Oil, Gas, Petrochemicals & Energy", description: "Reliable infrastructure, information security, dependable communications, high availability, and operational-center support for critical operations." },
            { id: "manufacturing", title: "Manufacturing & Factories", description: "Integrated infrastructure, stronger communications, higher efficiency, and readiness to digitize and intelligently evolve production operations." },
            { id: "financial-services", title: "Banks & Financial Institutions", description: "Security, continuity, availability, and information management designed for stable and scalable financial services." },
            { id: "government", title: "Government & Public Organizations", description: "Secure, resilient, and scalable foundations for electronic services and better citizen-facing delivery." },
            { id: "healthcare", title: "Healthcare Centers & Hospitals", description: "Reliable access to information, protection of sensitive data, and stable clinical systems that support quality care." },
            { id: "holdings", title: "Large Enterprises & Holdings", description: "Standardized and centrally managed technology foundations for organizations with multiple sites and complex operations." },
        ] },
        fa: { title: "صنایع", description: "راهکارهای فناوری متناسب با واقعیت صنایع انرژی، تولید، مالی، دولتی، درمانی و سازمان‌های بزرگ و چندسایتی.", payload: { breadcrumbLabel: "صنایع", hero: { badge: "صنایع هدف", title: "راهکارهایی متناسب با واقعیت هر صنعت", description: "هر پروژه را با فرآیندها، محدودیت‌ها و اهداف راهبردی همان صنعت آغاز می‌کنیم؛ نه با یک پشتهٔ فناوری از پیش آماده.", primaryAction: "مشاهده خدمات", secondaryAction: "مشاهده پروژه‌ها" }, section: { eyebrow: "صنایع هدف", title: "فناوری هم‌راستا با زمینهٔ عملیاتی", description: "معماری و اولویت‌های اجرا با شرایطی تنظیم می‌شوند که در هر صنعت اهمیت دارند." }, cta: { eyebrow: "هم‌راستایی صنعتی", title: "برای واقعیت‌های صنعت خود برنامه‌ریزی کنید", description: "با ارزیابی متمرکز عملیات حیاتی، ریسک‌ها و فرصت‌های رشد آغاز کنید.", action: "درخواست ارزیابی" } }, cards: [
            { id: "energy-petrochemicals", title: "نفت، گاز، پتروشیمی و انرژی", description: "زیرساخت پایدار، امنیت اطلاعات، ارتباطات مطمئن، دسترس‌پذیری بالا و پشتیبانی از مراکز عملیاتی برای عملیات حیاتی." },
            { id: "manufacturing", title: "صنایع تولیدی و کارخانه‌ها", description: "زیرساخت یکپارچه، ارتباطات بهتر، بهره‌وری بیشتر و آمادگی برای دیجیتالی و هوشمند کردن عملیات تولید." },
            { id: "financial-services", title: "بانک‌ها و مؤسسات مالی", description: "امنیت، تداوم خدمات، دسترس‌پذیری و مدیریت اطلاعات برای خدمات مالی پایدار و توسعه‌پذیر." },
            { id: "government", title: "سازمان‌ها و نهادهای دولتی", description: "زیرساخت امن، پایدار و مقیاس‌پذیر برای توسعهٔ خدمات الکترونیکی و خدمت‌رسانی بهتر به شهروندان." },
            { id: "healthcare", title: "مراکز درمانی و بیمارستان‌ها", description: "دسترسی قابل‌اعتماد به اطلاعات، حفاظت از داده‌های حساس و سامانه‌های درمانی پایدار برای پشتیبانی از کیفیت خدمات." },
            { id: "holdings", title: "شرکت‌های بزرگ و هلدینگ‌ها", description: "زیرساخت‌های استاندارد و مدیریت‌شدهٔ متمرکز برای سازمان‌های چندسایتی و دارای عملیات پیچیده." },
        ] },
    },
    solutions: {
        en: { title: "Solutions", description: "Integrated solution tracks that combine Arandi capabilities around real organizational priorities.", payload: { breadcrumbLabel: "Solutions", hero: { badge: "Integrated solutions", title: "From a priority to an executable solution", description: "We assemble the right capabilities into a clear path for resilient operations, secure transformation, and intelligent growth.", primaryAction: "View services", secondaryAction: "Contact us" }, catalog: { eyebrow: "Solution tracks", title: "Connected solutions for organizational outcomes", description: "Each track combines the services needed to address a concrete organizational challenge." }, delivery: { eyebrow: "Our journey", title: "A practical transformation path", steps: [{ key: "discover", label: "Discover", text: "Understand current conditions, critical needs, and organizational goals." }, { key: "strategy", label: "Strategy", text: "Define a focused roadmap, priorities, and governance." }, { key: "build-secure", label: "Build & Secure", text: "Implement the architecture with security and resilience built in." }, { key: "transform-operate", label: "Transform & Operate", text: "Embed intelligent capabilities and sustain them through managed operations." }] }, cta: { eyebrow: "Planning", title: "Choose a practical route forward", description: "We can map your needs to an integrated delivery path.", action: "Plan a conversation" } }, cards: [
            { id: "digital-foundation", title: "Digital Transformation Foundation", description: "A strategy-led roadmap that aligns IT architecture, business processes, technology choices, and implementation priorities.", secondary: "Clearer priorities, reduced risk, and a durable foundation for change" },
            { id: "secure-modern-infrastructure", title: "Secure Modern Infrastructure", description: "Integrated network, data center, cloud, server, and cybersecurity capabilities for stable and scalable digital services.", secondary: "Higher availability, stronger protection, and future-ready capacity" },
            { id: "enterprise-collaboration", title: "Connected Enterprise Operations", description: "Enterprise communications, collaboration, portals, and physical-security systems designed as a coherent ecosystem.", secondary: "More effective collaboration and better service experience" },
            { id: "ai-knowledge-operations", title: "AI, Knowledge & Managed Operations", description: "Enterprise AI, intelligent search, automation, monitoring, and managed IT services that make knowledge and operations more effective.", secondary: "Faster decisions, higher productivity, and continuously improved operations" },
        ] },
        fa: { title: "راهکارها", description: "مسیرهای راهکار یکپارچه که توانمندی‌های آرندی را حول اولویت‌های واقعی سازمان گرد هم می‌آورند.", payload: { breadcrumbLabel: "راهکارها", hero: { badge: "راهکارهای یکپارچه", title: "از یک اولویت تا راهکاری قابل‌اجرا", description: "توانمندی‌های مناسب را در مسیری روشن برای عملیات پایدار، تحول امن و رشد هوشمند کنار هم قرار می‌دهیم.", primaryAction: "مشاهده خدمات", secondaryAction: "تماس با ما" }, catalog: { eyebrow: "مسیرهای راهکار", title: "راهکارهای پیوسته برای نتایج سازمانی", description: "هر مسیر، خدمات لازم را برای پاسخ به یک چالش مشخص سازمانی ترکیب می‌کند." }, delivery: { eyebrow: "مسیر همکاری", title: "یک مسیر عملی برای تحول", steps: [{ key: "discover", label: "شناخت", text: "وضعیت موجود، نیازهای حیاتی و اهداف سازمان را درک می‌کنیم." }, { key: "strategy", label: "راهبرد", text: "نقشه‌راه، اولویت‌ها و حاکمیت اجرایی متمرکز را تعریف می‌کنیم." }, { key: "build-secure", label: "ساخت و ایمن‌سازی", text: "معماری را با امنیت و تاب‌آوریِ درونی اجرا می‌کنیم." }, { key: "transform-operate", label: "تحول و بهره‌برداری", text: "قابلیت‌های هوشمند را مستقر می‌کنیم و با بهره‌برداری مدیریت‌شده پایدارشان می‌سازیم." }] }, cta: { eyebrow: "برنامه‌ریزی", title: "مسیر عملی پیش‌روی خود را انتخاب کنید", description: "نیازهای شما را به یک مسیر تحویل یکپارچه نگاشت می‌کنیم.", action: "برنامه‌ریزی گفت‌وگو" } }, cards: [
            { id: "digital-foundation", title: "بنیان تحول دیجیتال", description: "نقشه‌راهی راهبردمحور که معماری IT، فرآیندهای کسب‌وکار، انتخاب فناوری و اولویت‌های اجرا را هم‌راستا می‌کند.", secondary: "اولویت‌های روشن‌تر، ریسک کمتر و بنیانی پایدار برای تغییر" },
            { id: "secure-modern-infrastructure", title: "زیرساخت مدرن و امن", description: "ترکیب شبکه، مرکز داده، رایانش ابری، سرورها و امنیت سایبری برای خدمات دیجیتال پایدار و مقیاس‌پذیر.", secondary: "دسترس‌پذیری بیشتر، حفاظت قوی‌تر و ظرفیت آمادهٔ آینده" },
            { id: "enterprise-collaboration", title: "عملیات سازمانی متصل", description: "ارتباطات، همکاری، پرتال‌ها و سامانه‌های امنیت فیزیکی سازمان در قالب یک اکوسیستم هماهنگ.", secondary: "همکاری مؤثرتر و تجربهٔ بهتر ارائهٔ خدمات" },
            { id: "ai-knowledge-operations", title: "هوش مصنوعی، دانش و بهره‌برداری", description: "هوش مصنوعی سازمانی، جست‌وجوی هوشمند، اتوماسیون، مانیتورینگ و خدمات مدیریت‌شده برای اثربخشی بیشتر دانش و عملیات.", secondary: "تصمیم‌گیری سریع‌تر، بهره‌وری بالاتر و بهبود مستمر عملیات" },
        ] },
    },
    projects: {
        en: { title: "Projects", description: "Selected Arandi projects across petrochemicals, commercial facilities, and manufacturing operations.", payload: { breadcrumbLabel: "Projects", hero: { badge: "Selected projects", title: "Technology delivery in real operating environments", description: "A selection of engagements described in Arandi’s company profile.", primaryAction: "Explore industries", secondaryAction: "Contact us" }, section: { eyebrow: "Project portfolio", title: "Representative engagements", description: "Selected examples of infrastructure, digital operations, and managed-service delivery." }, cta: { eyebrow: "Your project", title: "Plan the next initiative with clarity", description: "We can begin with scope, risks, and the outcomes that matter to your organization.", action: "Discuss your project" } }, cards: [
            { id: "persian-gulf-petrochemical", title: "Persian Gulf Petrochemical Complex", description: "IT infrastructure and technology services for a major petrochemical operating environment.", secondary: "Infrastructure services for a critical industrial context" },
            { id: "sonqor-methylamine", title: "Sonqor Petrochemical Methylamine Project", description: "Project IT infrastructure, digital operations support, specialized software, and knowledge-management services for the Methylamine project.", secondary: "A unified IT ecosystem across the project site and headquarters" },
            { id: "negin-zafar", title: "Negin Zafar Shopping Center", description: "Structured cabling, enterprise wireless, and shared communications infrastructure for an office and commercial facility.", secondary: "Reliable connectivity and integrated workplace services" },
            { id: "noorin-bonyad", title: "Noorin Bonyad Manufacturing Plant", description: "Managed IT services, network and virtualization support, data protection, security, VoIP, and help desk across multiple sites.", secondary: "Centralized, preventive IT management for multi-site operations" },
        ] },
        fa: { title: "پروژه‌ها", description: "نمونه‌ای از پروژه‌های آرندی در حوزه‌های پتروشیمی، فضاهای تجاری و عملیات تولیدی.", payload: { breadcrumbLabel: "پروژه‌ها", hero: { badge: "پروژه‌های منتخب", title: "تحویل فناوری در محیط‌های عملیاتی واقعی", description: "نمونه‌ای از همکاری‌هایی که در پروفایل شرکت آرندی معرفی شده‌اند.", primaryAction: "مشاهده صنایع", secondaryAction: "تماس با ما" }, section: { eyebrow: "سبد پروژه", title: "نمونه همکاری‌ها", description: "نمونه‌هایی از تحویل زیرساخت، عملیات دیجیتال و خدمات مدیریت‌شده." }, cta: { eyebrow: "پروژه شما", title: "ابتکار بعدی را با شفافیت برنامه‌ریزی کنید", description: "می‌توانیم از محدوده، ریسک‌ها و نتایج مهم برای سازمان شما آغاز کنیم.", action: "گفت‌وگو درباره پروژه" } }, cards: [
            { id: "persian-gulf-petrochemical", title: "مجتمع پتروشیمی خلیج فارس", description: "ارائهٔ زیرساخت فناوری اطلاعات و خدمات فناوری برای یک محیط عملیاتی بزرگ پتروشیمی.", secondary: "خدمات زیرساختی برای یک بستر صنعتی حیاتی" },
            { id: "sonqor-methylamine", title: "پروژه متیل‌آمین پتروشیمی سنقر", description: "زیرساخت فناوری اطلاعات پروژه، پشتیبانی از عملیات دیجیتال، نرم‌افزارهای تخصصی و مدیریت دانش برای پروژه متیل‌آمین.", secondary: "اکوسیستم یکپارچهٔ IT میان سایت پروژه و دفتر مرکزی" },
            { id: "negin-zafar", title: "مرکز خرید نگین ظفر", description: "کابل‌کشی ساخت‌یافته، شبکهٔ بی‌سیم سازمانی و زیرساخت ارتباطی مشترک برای مجموعهٔ اداری و تجاری.", secondary: "اتصال قابل‌اعتماد و خدمات محیط کار یکپارچه" },
            { id: "noorin-bonyad", title: "کارخانه تولیدی نورین‌بنیاد", description: "خدمات مدیریت‌شده IT، پشتیبانی شبکه و مجازی‌سازی، حفاظت از داده، امنیت، VoIP و هلپ‌دسک در چند سایت.", secondary: "مدیریت متمرکز و پیشگیرانهٔ IT برای عملیات چندسایتی" },
        ] },
    },
};

async function updateFixedPage(key: "company" | "contact") {
    const content = copy[key];
    await prisma.$transaction(async (tx) => {
        const page = await tx.page.findUniqueOrThrow({ where: { slug: key }, select: { id: true } });
        for (const language of ["en", "fa"] as const) {
            const item = content[language];
            await tx.pageTranslation.update({ where: { pageId_languageCode: { pageId: page.id, languageCode: language } }, data: { title: item.payload.breadcrumbLabel, seoTitle: item.title, seoDescription: item.description } });
            await tx.sectionTranslation.updateMany({ where: { section: { pageId: page.id, key: `${key}-content` }, languageCode: language }, data: { title: item.payload.breadcrumbLabel, description: item.description, data: json(item.payload) } });
        }
        await tx.page.update({ where: { id: page.id }, data: { seoKeywords: key === "company" ? ["Arandi", "digital transformation", "IT infrastructure", "AI"] : ["Arandi", "contact", "digital transformation"] } });
    }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable });
}

async function updateCollection(key: CollectionKey) {
    await prisma.$transaction(async (tx) => {
        const page = await tx.page.findUniqueOrThrow({ where: { slug: key }, select: { id: true } });
        const section = await tx.section.findFirstOrThrow({ where: { pageId: page.id, key: `${key}-catalog` }, select: { id: true } });
        for (const language of ["en", "fa"] as const) {
            const item = collections[key][language];
            await tx.pageTranslation.update({ where: { pageId_languageCode: { pageId: page.id, languageCode: language } }, data: { title: item.payload.breadcrumbLabel as string, seoTitle: item.title, seoDescription: item.description } });
            await tx.sectionTranslation.updateMany({ where: { sectionId: section.id, languageCode: language }, data: { title: item.payload.breadcrumbLabel as string, description: item.description, data: json(item.payload) } });
        }
        await tx.card.deleteMany({ where: { sectionId: section.id } });
        for (const [index, en] of collections[key].en.cards.entries()) {
            const fa = collections[key].fa.cards.find((card) => card.id === en.id);
            if (!fa) throw new Error(`Missing Persian card for ${key}:${en.id}`);
            await tx.card.create({ data: { key: `enterprise:${key}:${en.id}`, sectionId: section.id, variant: `${key.slice(0, -1)}Card`, order: index + 1, publishState: "published", tags: [key, "company-profile"], metrics: json({}), payload: json({ sourceKey: en.id, schemaVersion: 1, source: "Arandi_Company_Profile_Final" }), translations: { create: [{ languageCode: "en", title: en.title, description: en.description, subtitle: en.secondary ?? null, statusBadge: en.badge ?? null }, { languageCode: "fa", title: fa.title, description: fa.description, subtitle: fa.secondary ?? null, statusBadge: fa.badge ?? null }] } } });
        }
        await tx.page.update({ where: { id: page.id }, data: { seoKeywords: ["Arandi", key, "company-profile"] } });
    }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable });
}

async function updateSettings() {
    await prisma.setting.update({ where: { key: "site.company" }, data: { value: json({ en: { name: "Arandi", shortName: "Arandi", assistantName: "Arandi Assistant", assistantLabel: "Digital transformation assistant", footerTagline: "Committed to Results." }, fa: { name: "آرندی", shortName: "آرندی", assistantName: "دستیار آرندی", assistantLabel: "دستیار تحول دیجیتال", footerTagline: "متعهد به نتیجه." } }) } });
    await prisma.setting.update({ where: { key: "site.contact" }, data: { value: json({ en: { email: "info@arandi.io", phone: "+98 21 8609 5567", address: "Tehran, Jahanara Street, 23rd Street, No. 31, Unit 4", postalCode: "1438944614", website: "https://www.arandi.io" }, fa: { email: "info@arandi.io", phone: "۰۲۱-۸۶۰۹۵۵۶۷", address: "تهران، خیابان جهان‌آرا، خیابان بیست‌وسوم، پلاک ۳۱، واحد ۴", postalCode: "۱۴۳۸۹۴۴۶۱۴", website: "https://www.arandi.io" } }) } });
}

async function updateHomePage() {
    const home = await prisma.page.findUniqueOrThrow({ where: { slug: "home" }, select: { id: true } });
    const hero: Localized<Record<string, string | number | boolean>> = {
        en: { id: "hero", type: "hero", order: 1, enabled: true, badge: "Digital Transformation Partner", title: "From infrastructure to intelligence", description: "Arandi designs and delivers secure, reliable technology foundations—from IT infrastructure and cloud to enterprise AI and managed operations.", primaryCta: "Explore services", secondaryCta: "Contact Arandi" },
        fa: { id: "hero", type: "hero", order: 1, enabled: true, badge: "شریک تحول دیجیتال", title: "از زیرساخت تا هوشمندی", description: "آرندی بنیان‌های فناوری امن و پایدار را از زیرساخت و رایانش ابری تا هوش مصنوعی سازمانی و بهره‌برداری مدیریت‌شده طراحی و اجرا می‌کند.", primaryCta: "مشاهده خدمات", secondaryCta: "تماس با آرندی" },
    };
    const chat: Localized<Record<string, string | number | boolean>> = {
        en: { id: "chat", type: "chat", order: 2, enabled: true, badge: "AI Solutions", heading: "Explore practical enterprise AI possibilities", description: "Arandi designs AI solutions around real organizational data, knowledge, and processes.", placeholder: "Ask about AI, infrastructure, or transformation", initialMessage: "I can help outline enterprise AI, infrastructure, cybersecurity, and transformation priorities.", emptyStateTitle: "Start with a focused question.", emptyStateDescription: "Ask about a current challenge or a future capability.", inputLabel: "Ask Arandi", inputPlaceholder: "Ask about infrastructure, AI, or transformation...", inputAriaLabel: "Send message", loadingText: "Preparing a response...", assistantReply: "A focused response will be prepared here as part of the AI solution experience.", assistantHint: "Ask about architecture, delivery, or AI readiness" },
        fa: { id: "chat", type: "chat", order: 2, enabled: true, badge: "راهکارهای هوش مصنوعی", heading: "امکان‌های کاربردی هوش مصنوعی سازمانی را بررسی کنید", description: "آرندی راهکارهای هوش مصنوعی را بر پایهٔ داده‌ها، دانش و فرایندهای واقعی هر سازمان طراحی می‌کند.", placeholder: "دربارهٔ هوش مصنوعی، زیرساخت یا تحول بپرسید", initialMessage: "می‌توانم به ترسیم اولویت‌های هوش مصنوعی سازمانی، زیرساخت، امنیت سایبری و تحول کمک کنم.", emptyStateTitle: "با یک پرسش متمرکز شروع کنید.", emptyStateDescription: "دربارهٔ یک چالش فعلی یا یک قابلیت آینده سؤال کنید.", inputLabel: "از آرندی بپرسید", inputPlaceholder: "دربارهٔ زیرساخت، هوش مصنوعی یا تحول بپرسید...", inputAriaLabel: "ارسال پیام", loadingText: "در حال آماده‌سازی پاسخ...", assistantReply: "پاسخی متمرکز به‌عنوان بخشی از تجربهٔ راهکار هوش مصنوعی در اینجا آماده می‌شود.", assistantHint: "دربارهٔ معماری، اجرا یا آمادگی هوش مصنوعی بپرسید" },
    };
    const features: Localized<{ data: Record<string, string | number | boolean | string[]>; cards: Array<{ title: string; description: string; badge: string }> }> = {
        en: { data: { id: "features", type: "features", order: 3, enabled: true, eyebrow: "Core capabilities", title: "Engineering for every stage of transformation", description: "From strategy and architecture to secure delivery, intelligent operations, and long-term support.", serviceCardIds: ["digital-transformation-consulting", "infrastructure-network-data-center", "ai-solutions"] }, cards: [{ title: "Digital Transformation & IT Consulting", description: "Strategy, maturity assessment, roadmaps, architecture, and technology selection.", badge: "Strategy" }, { title: "Infrastructure, Network & Data Center", description: "Reliable foundations for critical services, connectivity, and future growth.", badge: "Infrastructure" }, { title: "Artificial Intelligence Solutions", description: "Enterprise AI, intelligent agents, knowledge management, search, and automation.", badge: "Intelligence" }] },
        fa: { data: { id: "features", type: "features", order: 3, enabled: true, eyebrow: "توانمندی‌های اصلی", title: "مهندسی برای همهٔ مراحل تحول", description: "از راهبرد و معماری تا اجرای امن، عملیات هوشمند و پشتیبانی بلندمدت.", serviceCardIds: ["digital-transformation-consulting", "infrastructure-network-data-center", "ai-solutions"] }, cards: [{ title: "مشاوره تحول دیجیتال و فناوری اطلاعات", description: "راهبرد، ارزیابی بلوغ، نقشه‌راه، معماری و انتخاب فناوری.", badge: "راهبرد" }, { title: "زیرساخت، شبکه و مرکز داده", description: "بنیان‌های قابل‌اعتماد برای سرویس‌های حیاتی، ارتباطات و رشد آینده.", badge: "زیرساخت" }, { title: "راهکارهای هوش مصنوعی", description: "هوش مصنوعی سازمانی، عامل‌های هوشمند، مدیریت دانش، جست‌وجو و اتوماسیون.", badge: "هوشمندی" }] },
    };
    await prisma.$transaction(async (tx) => {
        for (const language of ["en", "fa"] as const) {
            const localizedHero = hero[language];
            const localizedChat = chat[language];
            const localizedFeatures = features[language];
            await tx.pageTranslation.update({ where: { pageId_languageCode: { pageId: home.id, languageCode: language } }, data: { title: language === "fa" ? "صفحه اصلی" : "Home", seoTitle: language === "fa" ? "آرندی | شریک تحول دیجیتال" : "Arandi | Digital Transformation Partner", seoDescription: String(localizedHero.description) } });
            await tx.sectionTranslation.updateMany({ where: { section: { pageId: home.id, key: "hero" }, languageCode: language }, data: { title: String(localizedHero.title), subtitle: String(localizedHero.badge), description: String(localizedHero.description), data: json(localizedHero) } });
            await tx.sectionTranslation.updateMany({ where: { section: { pageId: home.id, key: "chat" }, languageCode: language }, data: { title: String(localizedChat.heading), subtitle: String(localizedChat.badge), description: String(localizedChat.description), data: json(localizedChat) } });
            await tx.sectionTranslation.updateMany({ where: { section: { pageId: home.id, key: "features" }, languageCode: language }, data: { title: String(localizedFeatures.data.title), subtitle: String(localizedFeatures.data.eyebrow), description: String(localizedFeatures.data.description), data: json(localizedFeatures.data) } });
        }
        const section = await tx.section.findFirstOrThrow({ where: { pageId: home.id, key: "features" }, select: { id: true } });
        await tx.card.deleteMany({ where: { sectionId: section.id } });
        for (const [index, en] of features.en.cards.entries()) {
            const fa = features.fa.cards[index];
            await tx.card.create({ data: { key: `home:capability:${index + 1}`, sectionId: section.id, variant: "serviceCard", order: index + 1, publishState: "published", tags: ["company-profile", "capability"], metrics: json({}), payload: json({ source: "Arandi_Company_Profile_Final" }), translations: { create: [{ languageCode: "en", title: en.title, description: en.description, statusBadge: en.badge }, { languageCode: "fa", title: fa.title, description: fa.description, statusBadge: fa.badge }] } } });
        }
        await tx.page.update({ where: { id: home.id }, data: { seoKeywords: ["Arandi", "digital transformation", "IT infrastructure", "cybersecurity", "cloud", "AI"] } });
    }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable });
}

async function main() {
    await updateFixedPage("company");
    await updateFixedPage("contact");
    for (const key of ["services", "solutions", "industries", "projects"] as const) await updateCollection(key);
    await updateSettings();
    await updateHomePage();
    console.log("Imported Arandi company profile content into published CMS records.");
}

main().finally(() => prisma.$disconnect());
