import { Prisma } from "@prisma/client";

import { prisma } from "@/lib/prisma";

const details = {
    "bid-boland-gas-gathering": {
        en: { client: "Petroniro Saba — Bid Boland Gas Gathering Project", industry: "Oil, gas & energy", overview: "Arandi delivered integrated IT services to establish resilient communications, increase service availability, connect project sites and offices, and support project execution and management processes.", scope: ["Network and server design, deployment, and support", "Secure site-to-office connectivity, remote access, VoIP, and network security", "Management of Change system and project-information monitoring", "Material control and daily, weekly, and monthly project reporting"], technologies: ["Active Directory and DNS", "VLAN segmentation", "DMVPN / VPN secure connectivity", "VoIP and organizational digital services"], outcome: "An integrated IT foundation that connected project sites and offices and gave project managers and teams access to the services and information they needed." },
        fa: { client: "شرکت پترونیروصبا — پروژه جمع‌آوری گازهای بیدبلند", industry: "نفت، گاز و انرژی", overview: "مجموعه‌ای از خدمات فناوری اطلاعات برای ایجاد ارتباط پایدار، افزایش دسترس‌پذیری سرویس‌ها، یکپارچه‌سازی ارتباطات و پشتیبانی از فرایندهای اجرایی و مدیریتی پروژه ارائه شد.", scope: ["طراحی، راه‌اندازی و پشتیبانی شبکه و سرورها", "ارتباط امن میان سایت‌ها و دفاتر، دسترسی از راه دور، VoIP و امنیت شبکه", "طراحی و استقرار سامانه مدیریت تغییرات و پایش اطلاعات پروژه", "کنترل متریال و گزارش‌های روزانه، هفتگی و ماهانه"], technologies: ["Active Directory و DNS", "تفکیک شبکه با VLAN", "ارتباط امن DMVPN / VPN", "VoIP و سرویس‌های دیجیتال سازمانی"], outcome: "ایجاد بستری یکپارچه برای پشتیبانی فناوری اطلاعات پروژه، تسهیل ارتباط میان سایت‌ها و دفاتر و دسترسی مدیران و عوامل پروژه به اطلاعات و سرویس‌های موردنیاز." },
    },
    "sonqor-methylamine": {
        en: { client: "Petroniro Saba — Sonqor Petrochemical Methylamine Project", industry: "Oil, gas & petrochemicals", overview: "An integrated digital project environment was implemented to connect the workshop and head office, mechanize execution processes, and organize project information and knowledge.", scope: ["Network design, structured cabling, server and equipment configuration", "Secure file sharing, video conferencing, VoIP, remote access, monitoring, backup, and restore", "Piping Construction Software for engineering, quality, contracts, planning, and project control", "PRC procurement workflow and organizational knowledge management"], technologies: ["Enterprise networking and servers", "Backup/restore and endpoint protection", "Piping Construction Software", "PRC procurement system and knowledge base"], outcome: "A unified IT ecosystem spanning secure workshop-to-head-office connectivity, engineering and procurement automation, operational control, and project knowledge management." },
        fa: { client: "شرکت پترونیروصبا — پروژه متیل‌آمین پتروشیمی سنقر", industry: "نفت، گاز و پتروشیمی", overview: "مجموعه‌ای یکپارچه از خدمات فناوری اطلاعات برای ایجاد زیرساخت دیجیتال پروژه، اتصال کارگاه به دفتر مرکزی، مکانیزه‌سازی فرایندهای اجرایی و مدیریت اطلاعات و دانش پروژه اجرا شد.", scope: ["طراحی شبکه، کابل‌کشی و نصب و پیکربندی تجهیزات شبکه و سرور", "اشتراک‌گذاری امن فایل، ویدئوکنفرانس، VoIP، دسترسی از راه دور، مانیتورینگ، Backup و Restore", "سامانه Piping Construction برای دفتر فنی، کنترل کیفیت، قراردادها، برنامه‌ریزی و کنترل پروژه", "سامانه PRC برای خرید و تدارکات و مدیریت دانش سازمانی"], technologies: ["شبکه و سرورهای سازمانی", "پشتیبان‌گیری، بازیابی و آنتی‌ویروس سازمانی", "Piping Construction Software", "سامانه PRC و پایگاه دانش"], outcome: "ایجاد اکوسیستم یکپارچه IT از ارتباط امن کارگاه و دفتر مرکزی تا مکانیزه‌سازی مهندسی، تدارکات، کنترل عملیات و مدیریت دانش." },
    },
    "negin-zafar": {
        en: { client: "Negin Zafar Shopping Center", industry: "Office & commercial real estate", overview: "IT infrastructure was designed and deployed for tenants across a multi-unit office and commercial building with architectural constraints around the central server room.", scope: ["Distributed network architecture for units beyond direct-cabling limits", "Cat6 UTP structured cabling and technical path testing", "Enterprise wireless access points across the facility", "Foundations for VoIP, shared resources, network printers, and organizational services"], technologies: ["Cat6 UTP structured cabling", "Managed network equipment", "Enterprise Wi‑Fi access points", "VoIP-ready shared-services infrastructure"], outcome: "A stable, manageable, and expandable network designed around building constraints and the communication needs of a multi-unit complex." },
        fa: { client: "ساختمان مرکز خرید نگین ظفر", industry: "ساختمان اداری و تجاری", overview: "زیرساخت فناوری اطلاعات برای واحدهای مستقر در بخش‌های مختلف ساختمان با توجه به محدودیت‌های معماری و فاصله از اتاق سرور مرکزی طراحی و پیاده‌سازی شد.", scope: ["طراحی معماری شبکه توزیع‌شده برای واحدهای دور از اتاق سرور", "کابل‌کشی ساخت‌یافته Cat6 UTP و تست فنی مسیرهای ارتباطی", "پیاده‌سازی Access Pointهای سازمانی در بخش‌های مختلف مجموعه", "فراهم‌سازی بستر VoIP، منابع مشترک، پرینترهای شبکه و خدمات سازمانی"], technologies: ["کابل‌کشی ساخت‌یافته Cat6 UTP", "تجهیزات مدیریتی شبکه", "Access Point سازمانی", "زیرساخت سرویس‌های اشتراکی و VoIP"], outcome: "ایجاد زیرساخت شبکه‌ای پایدار، قابل مدیریت و توسعه‌پذیر، متناسب با محدودیت‌های معماری ساختمان و نیازهای ارتباطی مجموعه چندواحدی." },
    },
    "noorin-bonyad": {
        en: { client: "Noorin Bonyad Manufacturing Plant", industry: "Manufacturing & industry", overview: "Arandi managed and supported a multi-site IT environment covering three operational and administrative sites in two cities, connected through secure communications.", scope: ["Local and inter-site network monitoring, link quality control, incident resolution, and addressing management", "Virtualization, server, storage, and service monitoring with planned updates", "Backup verification, scheduling optimization, and recovery testing", "VoIP, access control, firewall monitoring, least privilege, help desk, documentation, and reporting"], technologies: ["Secure VPN and remote access", "Virtualization and virtual machines", "Backup and recovery testing", "VoIP, firewall, CCTV, and Help Desk"], outcome: "A centralized, preventive IT-management framework that strengthened connectivity, information security, data protection, service continuity, and operational resilience across multiple sites." },
        fa: { client: "کارخانه تولیدی نورین بنیاد", industry: "تولید و صنعت", overview: "راهبری و پشتیبانی یکپارچه زیرساخت فناوری اطلاعات مجموعه‌ای چندسایتی شامل سه سایت اداری و عملیاتی در دو شهر انجام شد.", scope: ["پایش شبکه‌های محلی و ارتباطات بین‌سایتی، کنترل کیفیت لینک‌ها و رفع اختلال", "پایش سرورها، محیط مجازی‌سازی، منابع پردازشی و اجرای به‌روزرسانی‌های برنامه‌ریزی‌شده", "مدیریت Backup، کنترل صحت نسخه‌ها و تست‌های دوره‌ای بازیابی", "مدیریت VoIP، دسترسی‌ها، فایروال، Help Desk، مستندسازی و گزارش‌دهی"], technologies: ["VPN و دسترسی از راه دور امن", "مجازی‌سازی و ماشین‌های مجازی", "پشتیبان‌گیری و تست بازیابی", "VoIP، فایروال، CCTV و Help Desk"], outcome: "ایجاد چارچوبی متمرکز و پیشگیرانه برای مدیریت IT یک مجموعه تولیدی چندسایتی، با تمرکز بر پایداری ارتباطات، امنیت، حفاظت از داده و تداوم سرویس‌ها." },
    },
} as const;

async function main() {
    await prisma.$transaction(async (tx) => {
        for (const [slug, projectDetails] of Object.entries(details)) {
            const card = await tx.card.findUniqueOrThrow({ where: { key: `enterprise:projects:${slug}` }, select: { id: true, payload: true } });
            const payload = card.payload && typeof card.payload === "object" && !Array.isArray(card.payload) ? card.payload as Record<string, unknown> : {};
            await tx.card.update({ where: { id: card.id }, data: { payload: { ...payload, projectDetails } as Prisma.InputJsonValue } });
        }
    }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable });
    console.log("Imported full bilingual project details from the Arandi company profile.");
}

main().finally(() => prisma.$disconnect());
